services:

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "80:80"
      - "6001:6001"
    volumes:
      - ../:/var/www/
      - ./nginx/sites/:/etc/nginx/conf.d/
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - docker-net
    depends_on:
      - php74
      - php83

  php74:
    build:
      context: ./php7.4
      args:
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
    container_name: php_7.4
    restart: always
    volumes:
      - ../:/var/www/
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - ./docker-php-memlimit.ini:/usr/local/etc/php/conf.d/docker-php-memlimit.ini
      - ./openssl.cnf:/etc/ssl/openssl.cnf
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - docker-net
    tty: true
    depends_on:
      - mariadb
      - redis

  php83:
    build:
      context: ./php8.3
      args:
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
    container_name: php_8.3
    restart: always
    volumes:
      - ../:/var/www/
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - ./docker-php-memlimit.ini:/usr/local/etc/php/conf.d/docker-php-memlimit.ini
      - ./openssl.cnf:/etc/ssl/openssl.cnf
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - docker-net
    tty: true
    depends_on:
      - mariadb
      - redis

  mariadb:
    image: mariadb:10.2.44
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: "atxsales_local"
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
    command: --sql-mode="NO_ENGINE_SUBSTITUTION"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 3s
      timeout: 2s
      retries: 5
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - atxsales_mariadb:/var/lib/mysql
    networks:
      - docker-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8001:80
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: "root"
      PMA_PASSWORD: ""
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
    volumes:
      - ./phpmyadmin/sessions:/var/lib/php/sessions
    networks:
      - docker-net
  
  postgres:
    build: ./postgres
    container_name: postgres
    restart: always
    tty: true
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ${DATA_LIB}/data/postgres:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - 5432:5432
    networks:
      - docker-net

  redis :
    image: redislabs/rejson:latest
    container_name: redis
    restart: always
    expose:
      - 6379
    networks:
      - docker-net

networks: 
  docker-net:
    driver: bridge

volumes:
  atxsales_mariadb:

