services:

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "80:80"
      - "6001:6001"
    volumes:
      - ../:/var/www/
      - ./nginx/sites/:/etc/nginx/conf.d/
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - docker-net
    depends_on:
      - php56
      - php72
      - php74
      - php83

  php56:
    build:
      context: ./php5.6
      args:
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
    container_name: php_5.6
    restart: always
    volumes:
      - ../:/var/www/
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - ./docker-php-memlimit.ini:/usr/local/etc/php/conf.d/docker-php-memlimit.ini
      - ./openssl.cnf:/etc/ssl/openssl.cnf
    networks:
      - docker-net
    tty: true
    depends_on:
      - mariadb
      - redis

  php72:
    build:
      context: ./php7.2
      args:
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
    container_name: php_7.2
    restart: always
    volumes:
      - ../:/var/www/
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - ./docker-php-memlimit.ini:/usr/local/etc/php/conf.d/docker-php-memlimit.ini
      - ./openssl.cnf:/etc/ssl/openssl.cnf
    networks:
      - docker-net
    tty: true
    depends_on:
      - mariadb
      - redis

  php74:
    build:
      context: ./php7.4
      args:
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
    container_name: php_7.4
    restart: always
    volumes:
      - ../:/var/www/
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - ./docker-php-memlimit.ini:/usr/local/etc/php/conf.d/docker-php-memlimit.ini
      - ./openssl.cnf:/etc/ssl/openssl.cnf
    networks:
      - docker-net
    tty: true
    depends_on:
      - mariadb
      - redis

  php83:
    build:
      context: ./php8.3
      args:
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
    container_name: php_8.3
    restart: always
    volumes:
      - ../:/var/www/
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - ./docker-php-memlimit.ini:/usr/local/etc/php/conf.d/docker-php-memlimit.ini
      - ./openssl.cnf:/etc/ssl/openssl.cnf
    networks:
      - docker-net
    tty: true
    depends_on:
      - mariadb
      - redis

  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ${DATA_LIB}/data/mariadb:/var/lib/mariadb
      - ./mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - 3308:3308
    networks:
      - docker-net

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - docker-net
  
  postgres:
    build: ./postgres
    container_name: postgres
    restart: always
    tty: true
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ${DATA_LIB}/data/postgres:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - 5432:5432
    networks:
      - docker-net

  redis :
    image: redislabs/rejson:latest
    container_name: redis
    restart: always
    expose:
      - 6379
    networks:
      - docker-net

networks: 
  docker-net:
    driver: bridge

